### ISSUE TITLE
这tabs刷新有问题啊

### ISSUE THREAD

**Issue by hongehuo** [alex-0407/ionic3-awesome#1]
http://localhost:8100/#/home/home浏览器一刷新就http://localhost:8100/#/home，下面的tabs就不见了

**Comment by artdong** [comment]
浏览器中都有这个问题吧，对手机上效果没影响。你看见谁家的浏览器中刷新不会隐藏tab？？

**Comment by hongehuo** [comment]
哈哈，不考虑web端那就没有整个页面刷新的概念。。。

**Comment by artdong** [comment]
@hongehuo 最新代码已经支持刷新浏览器，tabs不消失
