### ISSUE TITLE
点击apps-百度，腾讯等链接报错

### ISSUE THREAD

**Issue by xumingyi** [alex-0407/ionic3-awesome#3]
环境信息：
cli packages: (C:\Users\FTD_2014\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.0
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\FTD_2014\AppData\Local\Android\Sdk

Misc:

    backend : pro
报错信息：
ERROR TypeError: Cannot read property 'style' of null
    at 7.js:152
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5425)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask (polyfills.js:3)
    at i.isUsingGlobalCallback.invoke (polyfills.js:3)
    at n (polyfills.js:3)

**Comment by artdong** [comment]
this.browser.proObj = document.getElementById('progress');
this.browser.proObj.style.width = '100%';

检查progress是否存在
