### ISSUE TITLE
android编译出错，只有卸载cordova-plugin-wechat插件才能编译通过。

### ISSUE THREAD

**Issue by xumingyi** [alex-0407/ionic3-awesome#4]
版本信息：

cli packages: (C:\Users\FTD_2014\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.0
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\FTD_2014\AppData\Local\Android\Sdk

Misc:

    backend : pro

报错信息：
android\app\src\main\java\xu\li\cordova\wechat\Wechat.java:281: ????: ??????? Wechat?е???? getAppId??????
??????;
            final String savedAppid = getAppId(cordova.getActivity());
                                      ^
  ???: ??в???
  ???: Activity
  ???: ???????б???????????б???????
C:\11_WorkSpace_11\D\Downloads\ionic3-awesome-develop\platforms\android\app\src\main\java\xu\li\cordova\wechat\Wechat.java:600: ????: ??????????????????÷??? ????
 preferences
            appId = preferences.getString(WXAPPID_PROPERTY_KEY, "");
                    ^
2 ??????
 FAILED
27 actionable tasks: 5 executed, 22 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
[10:26:18]  lint finished in 4.53 s
Error: cmd: Command failed with exit code 1 Error output:
C:\11_WorkSpace_11\D\Downloads\ionic3-awesome-develop\platforms\android\app\src\main\java\xu\li\cordova\wechat\Wechat.java:281: ????: ??????? Wechat?е???? getAppId??????
??????;
            final String savedAppid = getAppId(cordova.getActivity());
                                      ^
  ???: ??в???
  ???: Activity
  ???: ???????б???????????б???????
C:\11_WorkSpace_11\D\Downloads\ionic3-awesome-develop\platforms\android\app\src\main\java\xu\li\cordova\wechat\Wechat.java:600: ????: ??????????????????÷??? ????
 preferences
            appId = preferences.getString(WXAPPID_PROPERTY_KEY, "");
                    ^
2 ??????

FAILURE: Build failed with an exception.

**Comment by artdong** [comment]
缺少 wechatappid
参照这个安装插件 https://github.com/xu-li/cordova-plugin-wechat

没用到这个插件卸载就行了
